### ISSUE TITLE
Support custom institution lists

### ISSUE THREAD

**Issue by michaelckelly** [plaid/project-csa#17]
We'll be supporting the ability to display a custom list of supported institutions with Project CSA.  This will allow you to filter out certain institutions that you may not be interested in supporting, provide support for additional institutions that Plaid may not yet support, and include a custom button/trigger to open the CSA view.

I've closed a few issues related to this feature:  https://github.com/plaid/project-csa/issues/13, https://github.com/plaid/project-csa/issues/14, https://github.com/plaid/project-csa/issues/15. 

Look for this to be released within the next two weeks.  I'll be sure to keep this issue updated, too.  Feel free to post any questions/comments/suggestions here as well!

**Comment by pbernasconi** [comment]
Curious as to how you're going to implement the institutions-filter. Maybe accepting an Array or proper JSON?
- Array - `data-institutions-exclude="['amex', 'schwab']"`
- JSON- `data-institutions-exclude="{'amex': false, 'schwab': false}"`

It'd also be nice to have a callback option for when the modal is `opened` and `closed`, although I'm not entirely sure that's possible through data attributes.

**Comment by michaelckelly** [comment]
We've just released support for [custom initializers](https://github.com/plaid/project-csa#step-2-custom-integration) - you control when the CSA module opens, which means you can design your own "select your institution" page and jump directly to a particular institution's credentials form.

@pbernasconi:

> Curious as to how you're going to implement the institutions-filter. Maybe accepting an Array or proper JSON?

With the custom initializers, you can design your own institution select view and control precisely which institutions are supported. 

> It'd also be nice to have a callback option for when the modal is opened and closed, although I'm not entirely sure that's possible through data attributes.

There are `onSuccess` and `onExit` callbacks. :)

**Comment by benissimo** [comment]
How does this address issue 13?
Is there a way to load Plaid onto a page so that the dialog opens without needing the user to click something?
I tried passing in `open()` to the `onLoad` callback but that results in Chrome blocking the dialog as if it were a popup. Are there any working examples of how to do this?

**Comment by benissimo** [comment]
I've also tried simply calling `open()` right after creating the handler.
That "works" but it results in this warning in the JS console:
`link-initialize.js:1 Unable to open Plaid Link: wait until your onLoad function has been called before attempting to call .open() on your Plaid Link handler.`

I'd like to find a way to open the Plaid dialog without needing a click, but also without triggering a warning in the console and without requiring the user to have enabled their browser to accept popups.

**Comment by betesh** [comment]
@benissimo After reverse-minifying https://cdn.plaid.com/link/stable/link-initialize.js, it is clear that the Plaid iframe has to finish loading before you can call `open()`.  This should work:

              $('iframe#plaid-link-iframe').on('load', function() { linkHandler.open() });

However, it takes a few seconds until this event is triggered, during which time the content of your page will be visible.  So you might want to put your own spinning loader icon or similar from when you load the page until this event if fired.

**Comment by benissimo** [comment]
As things stand, the console warning fires and then the dialog is loaded correctly anyway. So if Plaid-link is able to intercept and delay `open` when called too soon, why can't it offer a hook that does the same? The 'onLoad' hook would seem to do so but instead doesn't work (results in Chrome interpreting `open` as loading a popup).

Reverse-engineering the markup currently used by Plaid may work but seems brittle. What happens if Plaid ever changes the markup? Can we count on `iframe#plaid-link-iframe' being future proof?
